### PR TITLE
A Photo Browser and Popup Animations

### PR DESCRIPTION
**Pull request by kevincobain2000**

### CODE REVIEW

**Comment by kevincobain2000** [comment]
hi! Thanks for putting everything in one place.., Just wondering if any progress on this pull request?

**Comment by Alexintosh** [comment]
Sorry, I had not too much time to try the new suggestions. I will very soon!
Thanks for submitting!

On 12 May 2016 at 05:43, Pulkit Kathuria notifications@github.com wrote:

> hi! Thanks for putting everything in one place.., Just wondering if any
> progress on this pull request?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Alexintosh/Awesome-Ionic/pull/15#issuecomment-218651850

## 

_Alessio Delmonti *| *web_ and _mobile_ developer

_Save a tree. Print this e-mail only if it's necessary_

**Comment by kevincobain2000** [comment]
woo thanks Alex

**Comment by Alexintosh** [comment]
Sorry for being late, enjoy!

**Pull request merged**
